In [ ]:
# numpy 불러오기 
import numpy as np

arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


배열에 값 채우기


In [ ]:
# 0으로 초기화된 배열  > 이전에 사용한 값들이 있을 수 있기에 초기화 
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 빈 값으로 만들어진 배열 > 아래와 같이 이전 값들이 남아있음 
arr = np.empty((4,4))
print(arr)

[[1.59938773e-316 3.80430547e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.50008929e+248 4.31174539e-096 9.80058441e+252]
 [1.23971686e+224 2.59031995e-144 6.06003395e+233 1.06400250e+248]
 [2.59050167e-144 5.22286946e-143 2.66023306e-312 0.00000000e+000]]


In [ ]:
# 1로 가득찬 배열을 만든다
arr = np.ones((3,3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# 배열의 생성
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# ndarray 배열의 모양, 차수, 데이터 타입 확인

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 배열의 모양
arr.shape

(2, 3)

In [ ]:
# 배열의 차수
arr.ndim

2

In [ ]:
# 배열의 데이터 타입 
arr.dtype

dtype('int64')

In [ ]:
arr_float = arr.astype(np.float64)
arr_float.dtype

dtype('float64')

In [ ]:
arr_str = np.array(['1','2','3'])
arr_str.dtype

dtype('<U1')

In [ ]:
arr_int = arr_str.astype(np.int64)
arr_int.dtype

dtype('int64')

In [ ]:
# ndarray 배열의 연산

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

In [ ]:
arr1 + arr2

array([[ 6,  8],
       [10, 12]])

In [ ]:
np.add(arr1, arr2)

array([[ 6,  8],
       [10, 12]])

In [ ]:
arr1 * arr2

array([[ 5, 12],
       [21, 32]])

In [ ]:
np.multiply(arr1, arr2)

array([[ 5, 12],
       [21, 32]])

In [ ]:
# ndarray 배열 **슬라이싱 하기 **

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
arr.ndim

2

In [ ]:
arr_1 = arr[:2,1:3]  #[0~1인덱스만,1~3인덱스만]
print(arr_1)

[[2 3]
 [5 6]]


In [ ]:
arr[0,2]

3

In [ ]:
arr[[0,1,2],[2,0,1]]  #[[인덱스0,1,2],[각인덱스의2,0,1값]]

array([3, 4, 8])

In [ ]:
idx = arr > 3 
print(idx)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
print(arr[idx])

[4 5 6 7 8 9]


In [ ]:
redwine = np.loadtxt(fname='winequality-red.csv',delimiter=';',skiprows=1). # 구별자(;), 1행 skip(header라서 skip)
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [ ]:
# 합계 

print(redwine.sum())

152084.78194


In [ ]:
# 평균

print(redwine.mean())

7.926036165311652


In [ ]:
# 축(axis)    >> axis=0 세로, axis=1 가로
print(redwine.sum(axis=0))

[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]


In [ ]:
print(redwine.mean(axis=0))   # mean = 평균

[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [ ]:
# 슬라이싱 

redwine[:,0].mean()

8.31963727329581

In [ ]:
redwine.max(axis=0)

array([ 15.9    ,   1.58   ,   1.     ,  15.5    ,   0.611  ,  72.     ,
       289.     ,   1.00369,   4.01   ,   2.     ,  14.9    ,   8.     ])

In [ ]:
redwine.min(axis=0)

array([4.6    , 0.12   , 0.     , 0.9    , 0.012  , 1.     , 6.     ,
       0.99007, 2.74   , 0.33   , 8.4    , 3.     ])